import { jsPDF } from "jspdf";
import { toPng } from "html-to-image";
import { X, Printer, Download, Clock } from 'lucide-react';

const StaffDirectoryModal = ({ staff, onClose }) => {
  if (!staff) return null;

  const handleDownloadPDF = async () => {
    try {
      const element = document.getElementById("staff-directory-report");
      const imgData = await toPng(element, { backgroundColor: "#ffffff", pixelRatio: 2 });
      const pdf = new jsPDF("p", "mm", "a4");
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const rect = element.getBoundingClientRect();
      const pdfHeight = (rect.height * pdfWidth) / rect.width;

      pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
      pdf.save(`RC_Fitness_Staff_Directory_${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (error) {
      console.error("PDF generation failed:", error);
      alert("PDF Error: " + (error.message || JSON.stringify(error)));
    }
  };

  const totalStaff = staff.length;
  const sortedStaff = [...staff].sort((a, b) => a.fullName.localeCompare(b.fullName));

  return (
    <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-[100] backdrop-blur-sm p-4">
      <div className="bg-white w-full max-w-4xl rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        <div className="flex-1 overflow-y-auto custom-scrollbar relative">
          <div id="staff-directory-report" className="bg-white text-black p-10 md:p-14 w-full">
            
            <div className="flex justify-between items-start border-b-2 border-gray-200 pb-8 mb-8">
              <div>
                <h1 className="text-4xl font-black italic tracking-tighter text-red-600">RC FITNESS <span className="text-black">GYM</span></h1>
                <p className="text-gray-500 text-sm mt-2 font-medium">123 Fitness Avenue, Muscle City</p>
                <p className="text-gray-500 text-sm font-medium">Official Employee Directory</p>
              </div>
              <div className="text-right">
                <h2 className="text-3xl font-black text-gray-200 uppercase tracking-widest">Staff Roster</h2>
                <p className="text-sm font-bold mt-2 text-gray-800">Generated: {new Date().toLocaleDateString()}</p>
              </div>
            </div>

            <div className="mb-10 flex gap-12 border-b-2 border-gray-100 pb-8">
              <div>
                <h3 className="text-xs font-black text-gray-400 uppercase tracking-widest mb-2">Total Active Trainers</h3>
                <p className="text-2xl font-black text-gray-900">{totalStaff}</p>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-6 mb-10">
              {sortedStaff.length === 0 ? (
                <p className="col-span-2 text-center py-10 text-gray-400 font-bold">No staff members found.</p>
              ) : (
                sortedStaff.map((s, index) => (
                  <div key={s._id || index} className="flex flex-col p-6 border border-gray-200 rounded-2xl bg-gray-50">
                    <div className="flex items-start gap-4 mb-4">
                      <div className="w-12 h-12 bg-gray-200 rounded-xl flex items-center justify-center text-gray-500 font-black text-xl mb-4 uppercase shrink-0">
                        {s.fullName[0]}
                      </div>
                      <div>
                        <h4 className="text-lg font-black text-gray-900 uppercase italic tracking-tight">{s.fullName}</h4>
                        <p className="text-[11px] font-black text-red-600 uppercase tracking-widest mt-1">{s.shift || "Variable Shift"}</p>
                      </div>
                    </div>
                    
                    <div className="space-y-2 mt-auto">
                       <p className="text-sm font-bold text-gray-600">{s.email}</p>
                       <div className="flex items-center gap-2 text-[10px] font-bold uppercase text-gray-400">
                          <Clock size={12}/> 08:00 - 17:00 (Standard)
                       </div>
                    </div>
                  </div>
                ))
              )}
            </div>

            <div className="text-center pt-8 border-t-2 border-gray-200 mt-16">
              <p className="text-sm font-bold text-gray-800 mb-1">Generated by RC Fitness Center Management System</p>
              <p className="text-xs text-gray-400 font-medium">Internal Use Only.</p>
            </div>

          </div>
        </div>

        <div className="bg-gray-50 p-6 border-t border-gray-200 flex justify-end gap-4 relative z-10 hide-on-print">
          <button onClick={onClose} className="px-6 py-2.5 rounded-xl font-bold text-sm text-gray-600 hover:bg-gray-200 transition-colors flex items-center gap-2 cursor-pointer">
            <X size={16} /> Cancel
          </button>
          <button onClick={() => window.print()} className="px-6 py-2.5 rounded-xl font-bold text-sm bg-red-600 text-white hover:bg-red-700 transition-colors shadow-lg shadow-red-600/20 flex items-center gap-2 cursor-pointer">
            <Printer size={16} /> Print Directory
          </button>
          <button onClick={handleDownloadPDF} className="px-6 py-2.5 rounded-xl font-bold text-sm bg-black text-white hover:bg-gray-800 transition-colors shadow-lg shadow-black/20 flex items-center gap-2 cursor-pointer">
            <Download size={16} /> Download PDF
          </button>
        </div>
      </div>
    </div>
  );
};

export default StaffDirectoryModal;
